<?php
/**
 * Builds the full business knowledge export (Markdown and HTML).
 *
 * @package WPAIL\Discovery
 */

declare(strict_types=1);

namespace WPAIL\Discovery;

use WPAIL\Licensing\Features;
use WPAIL\Models\ActionModel;
use WPAIL\Models\AnswerModel;
use WPAIL\Models\BusinessModel;
use WPAIL\Models\FaqModel;
use WPAIL\Models\LocationModel;
use WPAIL\Models\ProofModel;
use WPAIL\Models\ServiceModel;
use WPAIL\Repositories\ActionRepository;
use WPAIL\Repositories\AnswerRepository;
use WPAIL\Repositories\BusinessRepository;
use WPAIL\Repositories\FaqRepository;
use WPAIL\Repositories\LocationRepository;
use WPAIL\Repositories\ProofRepository;
use WPAIL\Repositories\ServiceRepository;

class KnowledgePageGenerator {

	private BusinessModel $profile;

	/** @var array<ServiceModel> */
	private array $services;

	/** @var array<LocationModel> */
	private array $locations;

	/** @var array<FaqModel> */
	private array $faqs;

	/** @var array<ProofModel> */
	private array $proof;

	/** @var array<ActionModel> */
	private array $actions;

	/** @var array<AnswerModel> */
	private array $answers;

	/** @var array<int, string> */
	private array $service_names = [];

	/** @var array<int, string> */
	private array $location_names = [];

	/** @var array<int, string> */
	private array $faq_titles = [];

	/** @var array<int, string> */
	private array $proof_titles = [];

	/** @var array<int, string> */
	private array $action_labels = [];

	public function __construct() {
		$this->profile   = ( new BusinessRepository() )->get();
		$this->services  = ( new ServiceRepository() )->get_all();
		$this->locations = ( new LocationRepository() )->get_all();
		$this->faqs      = ( new FaqRepository() )->get_all( true );
		$this->proof     = ( new ProofRepository() )->get_all( true );
		$this->actions   = ( new ActionRepository() )->get_all( true );
		$this->answers   = Features::answers_enabled() ? ( new AnswerRepository() )->get_all() : [];

		foreach ( $this->services as $service ) {
			$this->service_names[ $service->id ] = $service->name;
		}
		foreach ( $this->locations as $location ) {
			$this->location_names[ $location->id ] = $location->name;
		}
		foreach ( $this->faqs as $faq ) {
			$this->faq_titles[ $faq->id ] = $faq->question;
		}
		foreach ( $this->proof as $item ) {
			$this->proof_titles[ $item->id ] = $item->headline;
		}
		foreach ( $this->actions as $action ) {
			$this->action_labels[ $action->id ] = $action->label;
		}
	}

	public function generate_markdown(): string {
		$lines   = $this->build_header_lines();
		$lines   = array_merge( $lines, $this->build_profile_md() );
		$lines   = array_merge( $lines, $this->build_services_md() );
		$lines   = array_merge( $lines, $this->build_locations_md() );
		$lines   = array_merge( $lines, $this->build_faqs_md() );
		$lines   = array_merge( $lines, $this->build_proof_md() );
		$lines   = array_merge( $lines, $this->build_actions_md() );
		$lines   = array_merge( $lines, $this->build_answers_md() );
		$lines[] = '';
		$lines[] = '---';
		$lines[] = '';
		$lines[] = '_Generated by [AI Layer for WordPress](https://wordpress.org/plugins/ai-layer/). Structured API: ' . rest_url( WPAIL_REST_NS . '/manifest' ) . '_';

		return implode( "\n", $lines ) . "\n";
	}

	public function generate_html(): string {
		$name         = $this->site_name();
		$md_url       = esc_url( home_url( '/ai-layer/knowledge.md' ) );
		$manifest_url = esc_url( rest_url( WPAIL_REST_NS . '/manifest' ) );
		$updated      = esc_html( $this->updated_at_label() );
		$json_ld      = wp_json_encode( $this->build_json_ld(), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );

		ob_start();
		?>
<!DOCTYPE html>
<html lang="<?php echo esc_attr( str_replace( '_', '-', get_locale() ) ); ?>">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?php echo esc_html( $name ); ?> &mdash; <?php esc_html_e( 'Business Knowledge', 'ai-layer' ); ?></title>
<meta name="description" content="<?php echo esc_attr( $this->site_description() ); ?>">
<?php if ( KnowledgePage::is_noindex() ) : ?>
<meta name="robots" content="noindex, nofollow">
<?php endif; ?>
<link rel="alternate" type="text/markdown" href="<?php echo esc_url( $md_url ); ?>">
<style>
*,*::before,*::after{box-sizing:border-box}
body{margin:0;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#fff;color:#1e293b;line-height:1.65}
a{color:#2563eb}
.wrap{max-width:920px;margin:0 auto;padding:40px 24px 80px}
header{border-bottom:1px solid #e2e8f0;padding-bottom:24px;margin-bottom:32px}
h1{font-size:2rem;margin:0 0 8px;color:#0f172a}
.lead{color:#475569;margin:0 0 12px;font-size:1.05rem}
.meta{color:#64748b;font-size:.875rem;margin:0}
nav.toc{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px 20px;margin-bottom:40px}
nav.toc strong{display:block;margin-bottom:8px;font-size:.75rem;text-transform:uppercase;letter-spacing:.06em;color:#64748b}
nav.toc ul{margin:0;padding-left:18px}
section{margin-bottom:48px}
h2{font-size:1.5rem;margin:0 0 16px;color:#0f172a;border-bottom:2px solid #e2e8f0;padding-bottom:8px}
article.entity{border:1px solid #e2e8f0;border-radius:8px;padding:20px 24px;margin-bottom:16px}
article.entity h3{margin:0 0 12px;font-size:1.15rem;color:#0f172a}
dl{margin:0}
dt{font-weight:600;color:#334155;margin-top:10px}
dd{margin:4px 0 0;padding:0;color:#475569}
ul.compact{margin:4px 0 0;padding-left:18px}
footer{margin-top:56px;padding-top:24px;border-top:1px solid #e2e8f0;color:#64748b;font-size:.85rem}
</style>
<?php if ( is_string( $json_ld ) ) : ?>
<script type="application/ld+json"><?php echo $json_ld; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></script>
<?php endif; ?>
</head>
<body>
<div class="wrap">
<header>
<h1><?php echo esc_html( $name ); ?></h1>
<p class="lead"><?php echo esc_html( $this->site_description() ); ?></p>
<p class="meta">
<?php
printf(
	/* translators: 1: last updated datetime, 2: markdown URL, 3: manifest URL */
	esc_html__( 'Last updated: %1$s · %2$s · %3$s', 'ai-layer' ),
	$updated,
	'<a href="' . esc_url( $md_url ) . '">' . esc_html__( 'Markdown version', 'ai-layer' ) . '</a>',
	'<a href="' . esc_url( $manifest_url ) . '">' . esc_html__( 'JSON manifest', 'ai-layer' ) . '</a>'
);
?>
</p>
</header>
<?php echo $this->build_toc_html(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
<?php echo $this->build_body_html(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?>
<footer>
<?php
printf(
	/* translators: %s: plugin link */
	esc_html__( 'Complete business knowledge export from %s. Prefer this page or the Markdown version for full structured content; use the REST API for programmatic access.', 'ai-layer' ),
	'<a href="https://wordpress.org/plugins/ai-layer/">AI Layer</a>'
);
?>
</footer>
</div>
</body>
</html>
		<?php
		return (string) ob_get_clean();
	}

	/** @return array<string> */
	private function build_header_lines(): array {
		$name = $this->site_name();

		return [
			"# {$name} — Complete Business Knowledge",
			'',
			'> ' . $this->site_description(),
			'',
			'**Last updated:** ' . $this->updated_at_label(),
			'**HTML version:** ' . home_url( '/ai-layer/knowledge' ),
			'**Markdown version:** ' . home_url( '/ai-layer/knowledge.md' ),
			'**Structured API:** ' . rest_url( WPAIL_REST_NS . '/manifest' ),
			'',
			'## Contents',
			'',
			'- [Business profile](#profile)',
			'- [Services](#services)',
			'- [Locations](#locations)',
			'- [FAQs](#faqs)',
			'- [Proof and trust](#proof)',
			'- [Actions](#actions)',
			...( Features::answers_enabled() ? [ '- [Authored answers](#answers)', '' ] : [ '' ] ),
		];
	}

	/** @return array<string> */
	private function build_profile_md(): array {
		$p     = $this->profile;
		$lines = [ '## Business profile {#profile}', '' ];

		$this->append_md_field( $lines, 'Name', $p->name );
		$this->append_md_field( $lines, 'Legal name', $p->legal_name );
		$this->append_md_field( $lines, 'Type', trim( $p->business_type . ( $p->subtype ? " ({$p->subtype})" : '' ) ) );
		$this->append_md_field( $lines, 'Summary', $p->short_summary );
		if ( $p->long_summary ) {
			$lines[] = $p->long_summary;
			$lines[] = '';
		}
		$this->append_md_field( $lines, 'Phone', $p->phone );
		$this->append_md_field( $lines, 'Email', $p->email );
		$this->append_md_field( $lines, 'Website', $p->website );
		$address = $this->format_address( $p );
		if ( $address ) {
			$lines[] = '**Address:** ' . $address;
			$lines[] = '';
		}
		$this->append_md_field( $lines, 'Opening hours', $p->opening_hours );
		$this->append_md_list( $lines, 'Service modes', $p->service_modes );
		$this->append_md_field( $lines, 'Trust summary', $p->trust_summary );

		$social = array_filter( [
			'Facebook'  => $p->social_facebook,
			'Twitter/X' => $p->social_twitter,
			'LinkedIn'  => $p->social_linkedin,
			'Instagram' => $p->social_instagram,
			'YouTube'   => $p->social_youtube,
		] );
		if ( ! empty( $social ) ) {
			$lines[] = '**Social:**';
			foreach ( $social as $label => $url ) {
				$lines[] = "- {$label}: {$url}";
			}
			$lines[] = '';
		}

		return $lines;
	}

	/** @return array<string> */
	private function build_services_md(): array {
		$lines = [ '## Services {#services}', '' ];
		if ( empty( $this->services ) ) {
			$lines[] = '_No services published._';
			$lines[] = '';
			return $lines;
		}

		foreach ( $this->services as $service ) {
			$anchor = 'service-' . $service->slug;
			$lines[] = "### {$service->name} {#{$anchor}}";
			$lines[] = '';
			$this->append_md_field( $lines, 'Category', $service->category );
			$this->append_md_field( $lines, 'Summary', $service->short_summary );
			if ( $service->long_summary ) {
				$lines[] = $service->long_summary;
				$lines[] = '';
			}
			$this->append_md_list( $lines, 'Keywords', $service->keywords );
			$this->append_md_list( $lines, 'Customer types', $service->customer_types );
			$this->append_md_list( $lines, 'Service modes', $service->service_modes );
			$this->append_md_list( $lines, 'Benefits', $service->benefits );
			if ( $service->pricing_type || null !== $service->from_price ) {
				$price = $service->pricing_type;
				if ( null !== $service->from_price ) {
					$price .= ' from ' . $service->from_price . ' ' . $service->currency;
				}
				if ( $service->price_notes ) {
					$price .= ' — ' . $service->price_notes;
				}
				$lines[] = '**Pricing:** ' . trim( $price );
				$lines[] = '';
			}
			$this->append_md_field( $lines, 'Related FAQs', $this->names_for_ids( $service->related_faq_ids, $this->faq_titles ) );
			$this->append_md_field( $lines, 'Related locations', $this->names_for_ids( $service->related_location_ids, $this->location_names ) );
			$this->append_md_field( $lines, 'Related proof', $this->names_for_ids( $service->related_proof_ids, $this->proof_titles ) );
			$this->append_md_field( $lines, 'Related actions', $this->names_for_ids( $service->related_action_ids, $this->action_labels ) );
			if ( $service->linked_page_url ) {
				$lines[] = '**Linked page:** ' . $service->linked_page_url;
				$lines[] = '';
			}
		}

		return $lines;
	}

	/** @return array<string> */
	private function build_locations_md(): array {
		$lines = [ '## Locations {#locations}', '' ];
		if ( empty( $this->locations ) ) {
			$lines[] = '_No locations published._';
			$lines[] = '';
			return $lines;
		}

		foreach ( $this->locations as $location ) {
			$lines[] = "### {$location->name} {#location-{$location->slug}}";
			$lines[] = '';
			$this->append_md_field( $lines, 'Type', $location->location_type );
			$this->append_md_field( $lines, 'Region', $location->region );
			$this->append_md_field( $lines, 'Country', $location->country );
			$this->append_md_list( $lines, 'Postcode prefixes', $location->postcode_prefixes );
			if ( $location->is_primary ) {
				$lines[] = '**Primary location:** yes';
				$lines[] = '';
			}
			if ( null !== $location->service_radius_km ) {
				$lines[] = '**Service radius:** ' . $location->service_radius_km . ' km';
				$lines[] = '';
			}
			$this->append_md_field( $lines, 'Summary', $location->summary );
			$this->append_md_field( $lines, 'Related services', $this->names_for_ids( $location->related_service_ids, $this->service_names ) );
			$this->append_md_field( $lines, 'Local proof', $this->names_for_ids( $location->local_proof_ids, $this->proof_titles ) );
		}

		return $lines;
	}

	/** @return array<string> */
	private function build_faqs_md(): array {
		$lines = [ '## FAQs {#faqs}', '' ];
		if ( empty( $this->faqs ) ) {
			$lines[] = '_No FAQs published._';
			$lines[] = '';
			return $lines;
		}

		foreach ( $this->faqs as $faq ) {
			$lines[] = "### {$faq->question} {#faq-{$faq->id}}";
			$lines[] = '';
			$lines[] = $faq->short_answer;
			$lines[] = '';
			if ( $faq->long_answer ) {
				$lines[] = $faq->long_answer;
				$lines[] = '';
			}
			$this->append_md_field( $lines, 'Related services', $this->names_for_ids( $faq->related_service_ids, $this->service_names ) );
			$this->append_md_field( $lines, 'Related locations', $this->names_for_ids( $faq->related_location_ids, $this->location_names ) );
		}

		return $lines;
	}

	/** @return array<string> */
	private function build_proof_md(): array {
		$lines = [ '## Proof and trust {#proof}', '' ];
		if ( empty( $this->proof ) ) {
			$lines[] = '_No proof items published._';
			$lines[] = '';
			return $lines;
		}

		foreach ( $this->proof as $item ) {
			$lines[] = "### {$item->headline} {#proof-{$item->id}}";
			$lines[] = '';
			$this->append_md_field( $lines, 'Type', $item->proof_type );
			if ( $item->content ) {
				$lines[] = $item->content;
				$lines[] = '';
			}
			$this->append_md_field( $lines, 'Source', trim( $item->source_name . ( $item->source_context ? " ({$item->source_context})" : '' ) ) );
			if ( null !== $item->rating ) {
				$lines[] = '**Rating:** ' . $item->rating;
				$lines[] = '';
			}
			$this->append_md_field( $lines, 'Related services', $this->names_for_ids( $item->related_service_ids, $this->service_names ) );
			$this->append_md_field( $lines, 'Related locations', $this->names_for_ids( $item->related_location_ids, $this->location_names ) );
		}

		return $lines;
	}

	/** @return array<string> */
	private function build_actions_md(): array {
		$lines = [ '## Actions {#actions}', '' ];
		if ( empty( $this->actions ) ) {
			$lines[] = '_No actions published._';
			$lines[] = '';
			return $lines;
		}

		foreach ( $this->actions as $action ) {
			$lines[] = "### {$action->label} {#action-{$action->id}}";
			$lines[] = '';
			$this->append_md_field( $lines, 'Type', $action->action_type );
			$this->append_md_field( $lines, 'Description', $action->description );
			if ( $action->phone ) {
				$lines[] = '**Phone:** ' . $action->phone;
				$lines[] = '';
			}
			if ( $action->url ) {
				$lines[] = '**URL:** ' . $action->url;
				$lines[] = '';
			}
			$this->append_md_field( $lines, 'Method', $action->method );
			$this->append_md_field( $lines, 'Related services', $this->names_for_ids( $action->related_service_ids, $this->service_names ) );
			$this->append_md_field( $lines, 'Related locations', $this->names_for_ids( $action->related_location_ids, $this->location_names ) );
		}

		return $lines;
	}

	/** @return array<string> */
	private function build_answers_md(): array {
		if ( ! Features::answers_enabled() ) {
			return [];
		}

		$lines = [ '## Authored answers {#answers}', '' ];
		if ( empty( $this->answers ) ) {
			$lines[] = '_No authored answers published._';
			$lines[] = '';
			return $lines;
		}

		foreach ( $this->answers as $index => $answer ) {
			$title = $answer->short_answer ?: __( 'Authored answer', 'ai-layer' );
			$lines[] = '### ' . wp_trim_words( $title, 12, '…' ) . ' {#answer-' . ( $answer->post_id ?? $index ) . '}';
			$lines[] = '';
			$this->append_md_field( $lines, 'Short answer', $answer->short_answer );
			if ( $answer->long_answer ) {
				$lines[] = $answer->long_answer;
				$lines[] = '';
			}
			$this->append_md_list( $lines, 'Query patterns', $answer->query_patterns );
			$this->append_md_field( $lines, 'Related services', $this->names_for_ids( $answer->related_service_ids, $this->service_names ) );
			$this->append_md_field( $lines, 'Related locations', $this->names_for_ids( $answer->related_location_ids, $this->location_names ) );
			$this->append_md_field( $lines, 'Next actions', $this->names_for_ids( $answer->next_action_ids, $this->action_labels ) );
			$this->append_md_field( $lines, 'Source FAQs', $this->names_for_ids( $answer->source_faq_ids, $this->faq_titles ) );
		}

		return $lines;
	}

	private function build_toc_html(): string {
		$items = [
			'profile'   => __( 'Business profile', 'ai-layer' ),
			'services'  => __( 'Services', 'ai-layer' ),
			'locations' => __( 'Locations', 'ai-layer' ),
			'faqs'      => __( 'FAQs', 'ai-layer' ),
			'proof'     => __( 'Proof and trust', 'ai-layer' ),
			'actions'   => __( 'Actions', 'ai-layer' ),
		];
		if ( Features::answers_enabled() ) {
			$items['answers'] = __( 'Authored answers', 'ai-layer' );
		}

		$html = '<nav class="toc" aria-label="' . esc_attr__( 'Contents', 'ai-layer' ) . '"><strong>' . esc_html__( 'Contents', 'ai-layer' ) . '</strong><ul>';
		foreach ( $items as $id => $label ) {
			$html .= '<li><a href="#' . esc_attr( $id ) . '">' . esc_html( $label ) . '</a></li>';
		}
		$html .= '</ul></nav>';

		return $html;
	}

	private function build_body_html(): string {
		$html  = $this->build_profile_html();
		$html .= $this->build_services_html();
		$html .= $this->build_locations_html();
		$html .= $this->build_faqs_html();
		$html .= $this->build_proof_html();
		$html .= $this->build_actions_html();
		$html .= $this->build_answers_html();

		return $html;
	}

	private function build_profile_html(): string {
		$p = $this->profile;

		return $this->section_open( 'profile', __( 'Business profile', 'ai-layer' ) )
			. $this->entity_dl( [
				__( 'Name', 'ai-layer' )           => $p->name,
				__( 'Legal name', 'ai-layer' )     => $p->legal_name,
				__( 'Type', 'ai-layer' )           => trim( $p->business_type . ( $p->subtype ? " ({$p->subtype})" : '' ) ),
				__( 'Summary', 'ai-layer' )        => $p->short_summary,
				__( 'Phone', 'ai-layer' )          => $p->phone,
				__( 'Email', 'ai-layer' )          => $p->email,
				__( 'Website', 'ai-layer' )        => $p->website,
				__( 'Address', 'ai-layer' )        => $this->format_address( $p ),
				__( 'Opening hours', 'ai-layer' )  => $p->opening_hours,
				__( 'Service modes', 'ai-layer' )  => implode( ', ', $p->service_modes ),
				__( 'Trust summary', 'ai-layer' )  => $p->trust_summary,
			] )
			. ( $p->long_summary ? '<p>' . esc_html( $p->long_summary ) . '</p>' : '' )
			. $this->section_close();
	}

	private function build_services_html(): string {
		$html = $this->section_open( 'services', __( 'Services', 'ai-layer' ) );
		if ( empty( $this->services ) ) {
			return $html . '<p><em>' . esc_html__( 'No services published.', 'ai-layer' ) . '</em></p>' . $this->section_close();
		}

		foreach ( $this->services as $service ) {
			$html .= '<article class="entity" id="service-' . esc_attr( $service->slug ) . '">';
			$html .= '<h3>' . esc_html( $service->name ) . '</h3>';
			$html .= $this->entity_dl( [
				__( 'Category', 'ai-layer' )          => $service->category,
				__( 'Summary', 'ai-layer' )           => $service->short_summary,
				__( 'Keywords', 'ai-layer' )          => implode( ', ', $service->keywords ),
				__( 'Related FAQs', 'ai-layer' )      => $this->names_for_ids( $service->related_faq_ids, $this->faq_titles ),
				__( 'Related locations', 'ai-layer' ) => $this->names_for_ids( $service->related_location_ids, $this->location_names ),
				__( 'Related proof', 'ai-layer' )     => $this->names_for_ids( $service->related_proof_ids, $this->proof_titles ),
				__( 'Related actions', 'ai-layer' )   => $this->names_for_ids( $service->related_action_ids, $this->action_labels ),
			] );
			if ( $service->long_summary ) {
				$html .= '<p>' . esc_html( $service->long_summary ) . '</p>';
			}
			$html .= '</article>';
		}

		return $html . $this->section_close();
	}

	private function build_locations_html(): string {
		$html = $this->section_open( 'locations', __( 'Locations', 'ai-layer' ) );
		if ( empty( $this->locations ) ) {
			return $html . '<p><em>' . esc_html__( 'No locations published.', 'ai-layer' ) . '</em></p>' . $this->section_close();
		}

		foreach ( $this->locations as $location ) {
			$html .= '<article class="entity" id="location-' . esc_attr( $location->slug ) . '">';
			$html .= '<h3>' . esc_html( $location->name ) . '</h3>';
			$html .= $this->entity_dl( [
				__( 'Region', 'ai-layer' )            => $location->region,
				__( 'Summary', 'ai-layer' )           => $location->summary,
				__( 'Related services', 'ai-layer' )  => $this->names_for_ids( $location->related_service_ids, $this->service_names ),
				__( 'Local proof', 'ai-layer' )       => $this->names_for_ids( $location->local_proof_ids, $this->proof_titles ),
			] );
			$html .= '</article>';
		}

		return $html . $this->section_close();
	}

	private function build_faqs_html(): string {
		$html = $this->section_open( 'faqs', __( 'FAQs', 'ai-layer' ) );
		if ( empty( $this->faqs ) ) {
			return $html . '<p><em>' . esc_html__( 'No FAQs published.', 'ai-layer' ) . '</em></p>' . $this->section_close();
		}

		foreach ( $this->faqs as $faq ) {
			$html .= '<article class="entity" id="faq-' . esc_attr( (string) $faq->id ) . '">';
			$html .= '<h3>' . esc_html( $faq->question ) . '</h3>';
			$html .= '<p>' . esc_html( $faq->short_answer ) . '</p>';
			if ( $faq->long_answer ) {
				$html .= '<p>' . esc_html( $faq->long_answer ) . '</p>';
			}
			$html .= $this->entity_dl( [
				__( 'Related services', 'ai-layer' )  => $this->names_for_ids( $faq->related_service_ids, $this->service_names ),
				__( 'Related locations', 'ai-layer' ) => $this->names_for_ids( $faq->related_location_ids, $this->location_names ),
			] );
			$html .= '</article>';
		}

		return $html . $this->section_close();
	}

	private function build_proof_html(): string {
		$html = $this->section_open( 'proof', __( 'Proof and trust', 'ai-layer' ) );
		if ( empty( $this->proof ) ) {
			return $html . '<p><em>' . esc_html__( 'No proof items published.', 'ai-layer' ) . '</em></p>' . $this->section_close();
		}

		foreach ( $this->proof as $item ) {
			$html .= '<article class="entity" id="proof-' . esc_attr( (string) $item->id ) . '">';
			$html .= '<h3>' . esc_html( $item->headline ) . '</h3>';
			if ( $item->content ) {
				$html .= '<p>' . esc_html( $item->content ) . '</p>';
			}
			$html .= $this->entity_dl( [
				__( 'Type', 'ai-layer' )              => $item->proof_type,
				__( 'Related services', 'ai-layer' )  => $this->names_for_ids( $item->related_service_ids, $this->service_names ),
				__( 'Related locations', 'ai-layer' ) => $this->names_for_ids( $item->related_location_ids, $this->location_names ),
			] );
			$html .= '</article>';
		}

		return $html . $this->section_close();
	}

	private function build_actions_html(): string {
		$html = $this->section_open( 'actions', __( 'Actions', 'ai-layer' ) );
		if ( empty( $this->actions ) ) {
			return $html . '<p><em>' . esc_html__( 'No actions published.', 'ai-layer' ) . '</em></p>' . $this->section_close();
		}

		foreach ( $this->actions as $action ) {
			$html .= '<article class="entity" id="action-' . esc_attr( (string) $action->id ) . '">';
			$html .= '<h3>' . esc_html( $action->label ) . '</h3>';
			$html .= $this->entity_dl( [
				__( 'Type', 'ai-layer' )              => $action->action_type,
				__( 'Description', 'ai-layer' )       => $action->description,
				__( 'Phone', 'ai-layer' )             => $action->phone,
				__( 'URL', 'ai-layer' )               => $action->url,
				__( 'Related services', 'ai-layer' )  => $this->names_for_ids( $action->related_service_ids, $this->service_names ),
			] );
			$html .= '</article>';
		}

		return $html . $this->section_close();
	}

	private function build_answers_html(): string {
		if ( ! Features::answers_enabled() || empty( $this->answers ) ) {
			return '';
		}

		$html = $this->section_open( 'answers', __( 'Authored answers', 'ai-layer' ) );
		foreach ( $this->answers as $index => $answer ) {
			$id    = $answer->post_id ?? $index;
			$html .= '<article class="entity" id="answer-' . esc_attr( (string) $id ) . '">';
			$html .= '<h3>' . esc_html( wp_trim_words( $answer->short_answer ?: __( 'Authored answer', 'ai-layer' ), 12, '…' ) ) . '</h3>';
			$html .= '<p>' . esc_html( $answer->short_answer ) . '</p>';
			if ( $answer->long_answer ) {
				$html .= '<p>' . esc_html( $answer->long_answer ) . '</p>';
			}
			$html .= $this->entity_dl( [
				__( 'Query patterns', 'ai-layer' )    => implode( ', ', $answer->query_patterns ),
				__( 'Related services', 'ai-layer' )  => $this->names_for_ids( $answer->related_service_ids, $this->service_names ),
				__( 'Next actions', 'ai-layer' )      => $this->names_for_ids( $answer->next_action_ids, $this->action_labels ),
			] );
			$html .= '</article>';
		}

		return $html . $this->section_close();
	}

	/** @return array<string, mixed> */
	private function build_json_ld(): array {
		$graph = [];

		$p = $this->profile;
		if ( $p->name ) {
			$org = [
				'@type'       => 'Organization',
				'name'        => $p->name,
				'description' => $p->short_summary,
				'url'         => $p->website ?: home_url(),
			];
			if ( $p->phone ) {
				$org['telephone'] = $p->phone;
			}
			$graph[] = $org;
		}

		if ( ! empty( $this->faqs ) ) {
			$graph[] = [
				'@type'      => 'FAQPage',
				'mainEntity' => array_map(
					static fn( FaqModel $faq ) => [
						'@type'          => 'Question',
						'name'           => $faq->question,
						'acceptedAnswer' => [
							'@type' => 'Answer',
							'text'  => $faq->short_answer,
						],
					],
					$this->faqs
				),
			];
		}

		if ( empty( $graph ) ) {
			return [];
		}

		return [
			'@context' => 'https://schema.org',
			'@graph'   => $graph,
		];
	}

	private function section_open( string $id, string $title ): string {
		return '<section id="' . esc_attr( $id ) . '"><h2>' . esc_html( $title ) . '</h2>';
	}

	private function section_close(): string {
		return '</section>';
	}

	/** @param array<string, string> $fields */
	private function entity_dl( array $fields ): string {
		$html = '<dl>';
		foreach ( $fields as $label => $value ) {
			$value = trim( $value );
			if ( '' === $value ) {
				continue;
			}
			$html .= '<dt>' . esc_html( $label ) . '</dt><dd>' . esc_html( $value ) . '</dd>';
		}
		$html .= '</dl>';

		return $html;
	}

	/** @param array<string> $lines */
	private function append_md_field( array &$lines, string $label, string $value ): void {
		$value = trim( $value );
		if ( '' === $value ) {
			return;
		}
		$lines[] = "**{$label}:** {$value}";
		$lines[] = '';
	}

	/** @param array<string> $lines @param array<string> $items */
	private function append_md_list( array &$lines, string $label, array $items ): void {
		$items = array_values( array_filter( array_map( 'trim', $items ) ) );
		if ( empty( $items ) ) {
			return;
		}
		$lines[] = "**{$label}:** " . implode( ', ', $items );
		$lines[] = '';
	}

	/** @param array<int> $ids @param array<int, string> $map */
	private function names_for_ids( array $ids, array $map ): string {
		$names = [];
		foreach ( $ids as $id ) {
			if ( isset( $map[ (int) $id ] ) ) {
				$names[] = $map[ (int) $id ];
			}
		}

		return implode( ', ', $names );
	}

	private function format_address( BusinessModel $profile ): string {
		$parts = array_filter( [
			$profile->address_line1,
			$profile->address_line2,
			$profile->city,
			$profile->county,
			$profile->postcode,
			$profile->country,
		] );

		return implode( ', ', $parts );
	}

	private function site_name(): string {
		return $this->profile->name ?: get_bloginfo( 'name' );
	}

	private function site_description(): string {
		$desc = $this->profile->short_summary ?: get_bloginfo( 'description' );

		return $desc ?: __( 'Complete structured business knowledge for this site.', 'ai-layer' );
	}

	private function updated_at_label(): string {
		global $wpdb;

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$max = $wpdb->get_var(
			$wpdb->prepare(
				"SELECT MAX(post_modified_gmt) FROM {$wpdb->posts} WHERE post_type IN (%s,%s,%s,%s,%s,%s) AND post_status = 'publish'",
				'wpail_service',
				'wpail_location',
				'wpail_faq',
				'wpail_proof',
				'wpail_action',
				'wpail_answer'
			)
		);

		return $max ? get_date_from_gmt( $max, 'c' ) : gmdate( 'c' );
	}
}
